//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код был создан программным средством.
//
//     Изменения в этом файле могут привести к неправильному поведению и будут утрачены, если
//     код создается повторно. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmoSearch
{


    public partial class SiteMaster
    {

        /// <summary>
        /// Элемент управления HeadContent.
        /// </summary>
        /// <remarks>
        /// Автоматически созданное поле.
        /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>
        /// Элемент управления MainContent.
        /// </summary>
        /// <remarks>
        /// Автоматически созданное поле.
        /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
